name: basic compilation with g++

on:
  push:
    branches: [ main ]

jobs:
  print_g++_version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up g++
        run:
          sudo apt update
          sudo apt install g++ -y

      - name: print compiler version
        run:
          g++ --version

      