name: basic compilation with g++

on:
  push:
    branches: [ main ]

jobs:
  print_compiler_version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: update
        run: sudo apt update

      - name: install compiler
        run:  sudo apt install g++ -y

      - name: print compiler version
        run:
          g++ --version

      